N=60;
mu=[5 5;0 0;5 0];
mu1=[5 5];
mu2=[0 0];
mu3=[5 0];
lambda=[0 1 1;4 0 0;6 1 0];
sigma=[5 0;0 5];
pw1=0.2;
pw2=0.3;
pw3=0.5;
pw=[0.2;0.3;0.5];
%data1=mvnrnd(mu1,sigma,N);%产生三组服从正态分布的二位数据
%data2=mvnrnd(mu2,sigma,N);
%data3=mvnrnd(mu3,sigma,N);
figure(1);%画出所有的数据点
hold on
scatter(data1(:,1),data1(:,2),'xr');
scatter(data2(:,1),data2(:,2),'ob');
scatter(data3(:,1),data3(:,2),'.k');
xlabel('x');
ylabel('y');
legend('class1','class2','class3');
px=pw'*mvnpdf(x,mu,sigma);
%px=pw1*mvnpdf(x,mu1,sigma)+pw2*mvnpdf(x,mu2,sigma)+pw3*mvnpdf(x,mu3,sigma);
%pw1x=(mvnpdf(x,mu1,sigma)*pw1)/px;
%pw2x=(mvnpdf(x,mu2,sigma)*pw2)/px;
%pw3x=(mvnpdf(x,mu3,sigma)*pw3)/px;
pwx=(mvnpdf(x,mu,sigma).*pw)/px;
%pwx=(normpdf(x,mu1,sigma)*pw)/px;
%pwx=[pw1x;pw2x;pw3x];
R=lambda*pwx;
Rax=sum(R,2);
target1=find(Rax==min(min(Rax)));%给出最小风险决策
fprintf('Considering all the risks,this dot belongs to class %d\n',target1);
target2=find(pwx==max(pwx));%给出最小错误率决策
fprintf('Ignoring all the risks,this dot belongs to class%d\n',target2);
x1=-10:0.1:10;
y1=-10:0.1:10;
[X,Y]=meshgrid(x1,y1);
F1=mvnpdf([X(:),Y(:)],mu1,sigma);
F2=mvnpdf([X(:),Y(:)],mu2,sigma);
F3=mvnpdf([X(:),Y(:)],mu3,sigma);
PX=F1*pw1+F2*pw2+F3*pw3;
PWX1=reshape(pw1*F1./PX,size(X));
PWX2=reshape(pw2*F2./PX,size(X));
PWX3=reshape(pw3*F3./PX,size(X));
P1=reshape(F1,size(X));
P2=reshape(F2,size(X));
P3=reshape(F3,size(X));
R1=lambda(1,1)*PWX1+lambda(1,2)*PWX2+lambda(1,3)*PWX3;
R2=lambda(2,1)*PWX1+lambda(2,2)*PWX2+lambda(2,3)*PWX3;
R3=lambda(3,1)*PWX1+lambda(3,2)*PWX2+lambda(3,3)*PWX3;
figure(2);
hold on;
a=mesh(X,Y,P1);
b=mesh(X,Y,P2);
c=mesh(X,Y,P3);
title('类条件密度');
set(a,'Facecolor','white','Edgecolor','red');
set(b,'Facecolor','white','Edgecolor','blue');
set(c,'Facecolor','white','Edgecolor','yellow');
legend('P(x|w1)','P(x|w2)','P(x|w3)');
xlabel('x');ylabel('y');zlabel('P');
scatter3(x(1),x(2),0);
figure(3);
subplot(2,2,1);
surf(X,Y,PWX1);
title('P(w1|x)');
shading flat;
xlabel('x');ylabel('y');zlabel('P');
subplot(2,2,2);
surf(X,Y,PWX2);
title('P(w2|x)');
shading flat;
xlabel('x');ylabel('y');zlabel('P');
subplot(2,2,3);
surf(X,Y,PWX3);
title('P(w3|x)');
shading flat;
xlabel('x');ylabel('y');zlabel('P');
subplot(2,2,4);
hold on
a=mesh(X,Y,PWX1);
b=mesh(X,Y,PWX2);
c=mesh(X,Y,PWX3);
title('P(w1|x),P(w2|x) and P(w3|x)');
set(a,'Facecolor','white','Edgecolor','red');
set(b,'Facecolor','white','Edgecolor','blue');
set(c,'Facecolor','white','Edgecolor','yellow');
legend('P(w1|x)','P(w2|x)','P(w3|x)');
xlabel('x');ylabel('y');zlabel('P');
figure(4);
hold on
a=mesh(X,Y,reshape(R1,size(X)));
b=mesh(X,Y,reshape(R2,size(X)));
c=mesh(X,Y,reshape(R3,size(X)));
set(a,'Facecolor','white','Edgecolor','red');
set(b,'Facecolor','white','Edgecolor','blue');
set(c,'Facecolor','white','Edgecolor','yellow');
legend('R(a1|x)','R(a2|x)','R(a3|x)');
xlabel('x');ylabel('y');zlabel('Loss');
title('Risks');
scatter3(x(1),x(2),0);
